version: '3.8'
services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: lnsel
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3308"
    networks:
      - app-network

  nodejs_app:
    build: .
    container_name: nodejs_app
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3309
      DB_USER: root
      DB_PASSWORD: lnsel
      DB_NAME: mydb
    ports:
      - "3080:3080"
    depends_on:
      - mysql_db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge