service: node-lambda-app

provider:
  name: aws
  runtime: nodejs18.x  # Use supported runtime
  region: us-east-1
  stage: prod

  httpApi:
    name: node-lambda-app-api
    disableDefaultEndpoint: false  # Keep the default endpoint active
    cors: true  # Optional if needed

functions:
  app:
    handler: src/handler.handler
    events:
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /about
          method: get
      - httpApi:
          path: /dummy
          method: get
      - httpApi:
          path: /users
          method: get
      - httpApi:
          path: /users
          method: post
      - httpApi:
          path: /products
          method: get
      - httpApi:
          path: /products
          method: post
      - httpApi:
          path: /customers
          method: get
      - httpApi:
          path: /customers
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
