service: lambda05

provider:
  name: aws
  runtime: nodejs18.x  # Use supported runtime
  region: us-east-1
  stage: prod

  httpApi:
    name: node-lambda-app-api
    disableDefaultEndpoint: false  # Keep the default endpoint active
    cors: true  # Optional if needed

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          Resource:
            - arn:aws:s3:::mylambda-bucket-images/*

functions:
  app:
    handler: src/handler.handler
    memorySize: 1024
    timeout: 30
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
      - httpApi:
          path: /
          method: get
      - httpApi:
          path: /about
          method: get
      - httpApi:
          path: /dummy
          method: get
      - httpApi:
          path: /users
          method: get
      - httpApi:
          path: /users
          method: post
      - httpApi:
          path: /products
          method: get
      - httpApi:
          path: /products
          method: post
      - httpApi:
          path: /customers
          method: get
      - httpApi:
          path: /customers
          method: post      
      - httpApi:
          path: /auth/login
          method: post
      - httpApi:
          path: /items
          method: get
      - httpApi:
          path: /items
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
    httpPort: 8040

resources:
  Resources:
    UploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: mylambda-bucket-images
