name: Deploy Node.js to AWS Lambda

on:
  push:
    branches:
      - lambda_00

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Zip Lambda Package
      run: zip -r function.zip . -x "node_modules/*" ".git/*" ".github/*"

    - name: Deploy to Lambda
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: ${{ secrets.LAMBDA_FUNCTION_NAME }}
        zip_file: function.zip
