name: Deploy to AWS via Serverless

on:
  push:
    branches:
      - lambda_00  # ✅ Only trigger on this branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install Serverless Framework v3
        run: npm install -g serverless@3

      - name: Show Serverless version
        run: sls --version

      - name: Deploy with Serverless Framework
        run: sls deploy --stage dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
